# Generated by Django 5.0.6 on 2024-06-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
